SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

CREATE TABLE `mcq` (
  `sno` INT NOT NULL AUTO_INCREMENT,
  `testid` VARCHAR(255) NOT NULL,
  `question` VARCHAR(255) NOT NULL,
  `option1` VARCHAR(255) NOT NULL,
  `option2` VARCHAR(255) NOT NULL,
  `option3` VARCHAR(255) NOT NULL,
  `option4` VARCHAR(255) NOT NULL,
  `answer` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`sno`)
)ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;
--
