SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

CREATE TABLE IF NOT EXISTS mtest (
    id INT AUTO_INCREMENT PRIMARY KEY,
    studentid INT NOT NULL,
    testid INT NOT NULL,
    marks_obtained INT NOT NULL,
    FOREIGN KEY (studentid) REFERENCES student(id) ON DELETE CASCADE,
    FOREIGN KEY (testid) REFERENCES test(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;
--
