SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";



CREATE TABLE IF NOT EXISTS student (

    id INT AUTO_INCREMENT PRIMARY KEY,
    sname VARCHAR(255) NOT NULL,
    srollno VARCHAR(255) NOT NULL,
    semail VARCHAR(255) UNIQUE NOT NULL,
    spno VARCHAR(20) NOT NULL,
    syear INT NOT NULL,
    spassword VARCHAR(255) NOT NULL


) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=6 ;

--