SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

CREATE TABLE IF NOT EXISTS teacher (
    id INT AUTO_INCREMENT PRIMARY KEY,
    tname VARCHAR(255) NOT NULL,
    tid VARCHAR(255) NOT NULL,
    temail VARCHAR(255) UNIQUE NOT NULL,
    tpno VARCHAR(20) NOT NULL,
    tpassword VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=6;
