SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

CREATE TABLE IF NOT EXISTS test (
    id INT AUTO_INCREMENT PRIMARY KEY,
    temail VARCHAR(255) NOT NULL,
    tid VARCHAR(255) NOT NULL,
    testid VARCHAR(255) NOT NULL,
    testName VARCHAR(255) NOT NULL,
    Date DATETIME NOT NULL,
    url VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;
--
